http://localhost:8080
-ks
Content-Type: application/json; charset=utf-8

GET /jwt?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDY5ODU3MTM5NjgsInVzZXJJZCI6ImNtY2N1dGNoQHN0YXJidWNrcy5jb20iLCJvaWQiOiIyZTlhYzUxMS0yOGQ4LTRmYjctOWFkZS04NTBjMzg0MzE1YjQiLCJuYW1lIjoiQ29ubmVyIE1jQ3V0Y2hlb24iLCJuYW1lUGFydHMiOnsiZmlyc3QiOiJDb25uZXIiLCJsYXN0IjoiTWNDdXRjaGVvbiJ9LCJzY29wZXMiOlsiZGV2aWNlczpjYW4tcXVlcnkiLCJ0ZW5hbnQ6ZGV2IiwidGVuYW50OmJpdHMiXSwiaWF0IjoxNTA2OTgyMTE1fQ.PfGh35wJMfgLURBlX6Ysm99LcwcHtcxObSpTeW6rBcbJzLQae_0CHi_OybigABOHZWz-PXSDIcDvE2O-SY55lHZkAVU733akfxqICbi9M_-vquNZFM2x_h-v8V9yF-Qz9E862Xz72RwnVXwuuGpRitgl4e6-NKLSMWCpJb5fswzAzLfwTfP-zUq4QpmVPBpiScTRmMw482U4h7-gJcS3TGOG00__Ov2F9SaCOdwMxhCfMJqn1btuuLMKA-ixMS1A6G5mmTzRrLFIE1HgIAaTrhuK2_UCGJcC6RNYkSQYJkf9vv0BOj2sOO6Oxy9dBBjgV07-I4lgL6M1K5L-j4mVcg
